name: Auto Update Packages

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger from the GitHub Actions UI

jobs:
  update-packages:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PowerShell & AU Module
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          Install-Module au -Force -Scope CurrentUser

      - name: Run AU Update Script
        shell: powershell
        run: |
          Set-Location "automatic\touchdesigner"
          ./update.ps1

      - name: Commit and Push Changes
        shell: powershell
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add -A
          $status = git status --porcelain
          if ($status) {
              git commit -m "(touchdesigner) Automatic update to latest version"
              git push
          } else {
              Write-Host "No package updates found."
          }